micronaut:
  application:
    name: spockExample
    server:
      port: 8080
datasources:
  default:
    url: jdbc:h2:mem:albumDB;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
    schema-generate: CREATE_DROP
    dialect: H2Dialect
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
    entity-scan:
      packages: 'com.globallogic.spockExample.*'
